# module 1 A Text file consisting of the solutions to each SQL requirement.

# 1) Which apps have the highest rating in the given available dataset?
select App from playstore.playstore_app_cleaned_after_load
where Rating = (select max(Rating) from playstore.playstore_app_cleaned_after_load);


# 2) What are the number of installs and reviews for the above apps? Return the apps with the highest reviews to the top.

select App ,Reviews,Installs from playstore.playstore_app_cleaned_after_load
where Rating = (select max(Rating) from playstore.playstore_app_cleaned_after_load)
order by 2 desc;

# 3) Which app has the highest number of reviews? Also, mention the number of reviews and category of the app

select App,Reviews,Category from playstore.playstore_app_cleaned_after_load
where Reviews = ( select max(Reviews) from playstore.playstore_app_cleaned_after_load);

# 4) What is the total amount of revenue generated by the google play store by hosting apps?
#(Whenever a user buys apps  from the google play store, the amount is considered in the revenue)

select sum(Price)  as revenue_generated 
from playstore.playstore_app_cleaned_after_load;

# 5)  Which Category of google play store apps has the highest number of installs? 
# also, find out the total number of installs for that particular category.


select Category,sum(Installs) as total_num_installs
from playstore.playstore_app_cleaned_after_load
group by Category
order by 2 desc
limit 1;

# 6) Which Genre has the most number of published apps?

select Genres ,count(*) as num_of_apps
from playstore.playstore_app_cleaned_after_load
group by 1
order by 2 desc
limit 1;

# 7) Provide the list of all games ordered in such a way that the game that has the highest number of installs is displayed on the top
#(to avoid duplicate results use distinct)

select distinct App,Installs
from playstore.playstore_app_cleaned_after_load
where Category = "GAME"
order by 2 desc
limit 10;

# 8) Provide the list of apps that can work on android version 4.0.3 and UP.

select App
from playstore.playstore_app_cleaned_after_load
where Android_ver 
 = '4.0.3 and up';
 
 # 9) How many apps from the given data set are free? Also, provide the number of paid apps.

select Type, count(Type)
from playstore.playstore_app_cleaned_after_load
where type in("Free","Paid")
group by 1;

# 10) Which is the best dating app? 
#(Best dating app is the one having the highest number of Reviews)

select *
from playstore.playstore_app_cleaned_after_load
where Genres = "Dating" and (select max(Reviews) from playstore.playstore_app_cleaned_after_load)
order by Reviews desc
limit 1;

# 11) Get the number of reviews having positive sentiment and number of reviews having negative sentiment for the app 10 best foods for you and compare them.

SELECT Sentiment, COUNT(Sentiment) As sentiments FROM playstore.playstore_review
WHERE  App = "10 best foods for you" AND Sentiment <> "Neutral"
GROUP BY Sentiment;

# 12) Which comments of ASUS SuperNote have sentiment polarity and sentiment subjectivity both as 1?


SELECT * FROM playstore.playstore_review
WHERE App = "ASUS SuperNote" 
AND Sentiment_Polarity = 1
AND Sentiment_Subjectivity = 1;

# 13) Get all the neutral sentiment reviews for the app Abs Training-Burn belly fat 

SELECT * 
FROM playstore_review 
WHERE Sentiment = "Neutral"
AND App = "Abs Training-Burn belly fat";

# 14) Extract all negative sentiment reviews for Adobe Acrobat Reader with their sentiment polarity and sentiment subjectivity

SELECT * FROM playstore.playstore_review
WHERE Sentiment = "Negative" AND App = "Adobe Acrobat Reader";
